@startuml Models
left to right direction
class Subject{
    id : INTEGER
    ..
    name : STRING
}


class Chapter{
    id : INTEGER
    ..
    name : STRING
    subject_id : INTEGER
}


class Question{
    id : INTEGER
    ..
    questionText : STRING
    difficulty : FLOAT
    addTime : DATETIME
    addPerson : STRING
    type : STRING
    chapter_id : INTEGER
}

class MutipleChoice{
    id : INTEGER
    ..
    choice1 : STRING
    choice2 : STRING
    choice3 : STRING
    choice4 : STRING
    answer : STRING
    questionId : INTEGER
}

class FillInTheBlanks{
    id : INTEGER
    ..
    answer : STRING
    questionId : INTEGER
}

class BrifeAnswers{
    id : INTEGER
    ..
    answer : STRING
    questionId : INTEGER
}

Subject::id *-- Chapter::subject_id
Chapter::id *-- Question::chapter_id
Question::id *-- MutipleChoice::questionId
Question::id *-- FillInTheBlanks::questionId
Question::id *-- BrifeAnswers::questionId

@enduml