@startuml Models
left to right direction
entity Subject{
    id : INTEGER
    ..
    name : STRING
    teacher_id : INTEGER
}


entity Chapter{
    id : INTEGER
    ..
    name : STRING
    subject_id : INTEGER
}


entity ExamPaper{
    id : INTEGER
}


entity Question{
    id : INTEGER
    ..
    questionText : STRING
    difficulty : FLOAT
    addTime : DATETIME
    addPerson : STRING
    type : STRING
    examPaper_id : INTEGER
    chapter_id : INTEGER
}

entity MutipleChoice{
    id : INTEGER
    ..
    choice1 : STRING
    choice2 : STRING
    choice3 : STRING
    choice4 : STRING
    answer : STRING
    questionId : INTEGER
}

entity FillInTheBlanks{
    id : INTEGER
    ..
    answer : STRING
    questionId : INTEGER
}


entity Teacher{
    id : INTEGER
    ..
    name : STRING
}


entity Classes{
    id : INTEGER
    ..
    teacher_id : INTEGER
}


entity Student{
    id : INTEGER
    ..
    classes_id : INTEGER
}


entity Score{
    id : INTEGER
    score : INTEGERs
    student_id : INTEGER
    examPaper_id : INTEGER
}


Teacher "1" ||-|{ "n" Classes: 老师-班级
Classes "m" }|--|{ "n" Student: 班级-学生
Student "m" }|--|{ "n" Score: 学生-试卷分数
Teacher "m" }|--|{ "n" Subject: 老师-学科
Subject "1" ||--|{ "n" Chapter: 学科-章节
Chapter "1" ||--|{ "n" Question: 章节-题目
Question "1" ||--|| "1" MutipleChoice: 问题-选择题
Question "1" ||--|| "1" FillInTheBlanks: 问题-填空题
ExamPaper "m" }|--|{ "n" Question: 试卷-题目
ExamPaper "m" }|--|{ "n" Score: 试卷-分数
@enduml