@startuml Models
left to right direction
class Subject{
    id : INTEGER
    ..
    subject_name : STRING
    questionId : INTEGER
}
class Question{
    id : INTEGER
    ..
    chapter : SRING
    questionText : STRING
    difficulty : FLOAT
    addTime : DATETIME
    addPerson : STRING
    type : STRING
}

class MutipleChoice{
    id : INTEGER
    ..
    choice1 : STRING
    choice2 : STRING
    choice3 : STRING
    choice4 : STRING
    answer : STRING
    questionId : INTEGER
}

class FillInTheBlanks{
    id : INTEGER
    ..
    answer : STRING
    questionId : INTEGER
}

class BrifeAnswers{
    id : INTEGER
    ..
    answer : STRING
    questionId : INTEGER
}

Question::id *-- MutipleChoice::questionId
Question::id *-- FillInTheBlanks::questionId
Question::id *-- BrifeAnswers::questionId
Question::id *-- Subject::questionId

@enduml