@startuml
(*)--> "登   录"
--> if "是  否  加  入  教  学  班" then
        [是]if "查  看  是  否  有  试  卷  发  布" then
            -->[是] "进  入  试  卷  开  始  答  题"
        else
            -->[否] "等  待  老  师  发  布  试  卷"
        endif
    else
        -->[否] "加  入  教  学  班"
    endif
@enduml