@startuml teacher
(*) --> "登   录"
if "是  否  有  科  目" then
    -right->[否] "创  建  科  目"
    --> ==b4==
else
    -->[是] ==b4==
    if "是  否  有  教  学  班" then
        -->[否] "创  建  教  学  班"
        --> ==b1==
        if "是  否  有  试  卷" then
            -->[是] "发  布  试  卷 到 指  定  教  学  班"
        else
            -right->[否] "创  建  试  卷"
            if "是  否  有  题  库" then
                -->[是] "将  题  目  加  入  试  卷"
            else
                -->[否] "创  建  题  库"
                --> "将  题  目  加  入  试  卷"
                --> "发  布  试  卷 到 指  定  教  学  班"
                
            endif
        endif
    else
        -->[是] ==b1==
endif

@enduml